---

- name: get fish
  unarchive:
    copy: no
    remote_src: yes
    src: "http://fishshell.com/files/{{ fish_version }}/fish-{{ fish_version }}.tar.gz"
    dest: /usr/src
    creates: "/usr/src/fish-{{ fish_version }}"

- name: configure fish
  command: "./configure"
  args:
    chdir: "/usr/src/fish-{{ fish_version }}"
    creates: "/usr/src/fish-{{ fish_version }}/Makefile"

- name: compile fish
  command: "gmake"
  args:
    chdir: "/usr/src/fish-{{ fish_version }}"
    creates: "/usr/src/fish-{{ fish_version }}/fish"

- name: install fish
  command: "gmake install"
  args:
    chdir: "/usr/src/fish-{{ fish_version }}"
    creates: "/usr/local/bin/fish"

- name: add fish to shells
  lineinfile:
    dest: /etc/shells
    state: present
    line: /usr/local/bin/fish

- name: set user shell to fish
  user:
    name: "{{ user }}"
    shell: /usr/local/bin/fish
