---

- hosts: laptop
  become: yes
  become_method: doas
  roles:
    - laptop

- hosts: router
  become: yes
  become_method: doas
  roles:
    - router

- hosts: pi
  become: yes
  become_method: doas
  roles:
    - pi
