---

- hosts: laptop
  become: yes
  become_method: doas
  vars_files:
    -  vault.yml
  roles:
    - laptop

- hosts: router
  become: yes
  become_method: doas
  vars_files:
    -  vault.yml
  roles:
    - router

- hosts: pi
  become: yes
  become_method: sudo
  vars_files:
    -  vault.yml
  roles:
    - pi
