---

- name: configure dhcpd
  copy:
    src: dhcpd.conf
    dest: /etc/dhcpd.conf
  notify: restart dhcpd

- name: configure dhcpd options
  lineinfile:
    dest: /etc/rc.conf.local
    line: dhcpd_flags=em1
    state: present
  notify: restart dhcpd

- name: start dhcpd
  service:
    name: dhcpd
    state: started
