---

- name: configure wifi
  template:
    dest: /etc/hostname.iwm0
    src: hostname.iwm0
  notify: configure interfaces

- name: install packages
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items:
    - chromium
    - dwm
    - firefox
    - git
    - gnupg
    - mpc
    - mplayer
    - ncmpc
    - password-store
    - pinentry-gtk2
    - vim
    - zsh

- name: configure pf
  copy:
    src: pf.conf
    dest: /etc/pf.conf
    mode: 0600
  notify: reload pf

- name: create user directories
  file:
    dest: "{{ item }}"
    state: directory
    group: "{{ user }}"
    owner: "{{ user }}"
  with_items:
    - "/home/{{ user }}/.vim/ftdetect"
    - "/home/{{ user }}/.config"

- name: configure user
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - src: Xresources
      dest: "/home/{{ user }}/.Xresources"
    - src: user-dirs.dirs
      dest: "/home/{{ user }}/.config/user-dirs.dirs"
    - src: vimrc
      dest: "/home/{{ user }}/.vimrc"
    - src: xsession
      dest: "/home/{{ user }}/.xsession"
    - src: yaml.vim
      dest: "/home/{{ user }}/.vim/ftdetect/yaml.vim"

- name: enable apmd
  lineinfile:
    dest: /etc/rc.conf.local
    line: apmd_flags=-A
    state: present
  notify: restart apmd
