---

- name: mail aliases
  lineinfile:
    line: "{{ item }}"
    dest: /etc/mail/aliases
    state: present
  with_items:
    - "root: {{ user }}"
    - "{{ user }}: {{ email }}"
  notify: new aliases

- name: configure smtpd
  template:
    src: smtpd.conf
    dest: /etc/mail/smtpd.conf
  notify: restart smtpd

- name: enable smtpd
  service:
    name: smtpd
    enabled: yes
    state: started
