---

- name: open vault
  include_vars:
    file: vault.yml

- name: install dhcpcd
  openbsd_pkg:
    name: dhcpcd
    state: present

- name: configure dhcpcd
  copy:
    src: dhcpcd.conf
    dest: /etc/dhcpcd.conf
  notify: reload dhcpcd

- name: enable dhcpcd
  service:
    name: dhcpcd
    state: started
    enabled: yes

- name: enable routing
  lineinfile:
    create: yes
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - net.inet.ip.forwarding=1
    - net.inet6.ip6.forwarding=1
  notify: enable routing

- name: configure pf
  copy:
    src: pf.conf
    dest: /etc/pf.conf
    mode: 0600
  notify: reload pf

- name: configure rtadvd flags
  lineinfile:
    dest: /etc/rc.conf.local
    line: rtadvd_flags=em1
    state: present
  notify: restart rtadvd

- name: configure interfaces
  copy:
    dest: "{{ item.dest }}"
    mode: 0600
    src: "{{ item.src }}"
  with_items:
    - src: hostname.em0
      dest: /etc/hostname.em0
    - src: hostname.em1
      dest: /etc/hostname.em1
  notify: enable interfaces

- name: configure pppoe
  template:
    dest: /etc/hostname.pppoe0
    mode: 0600
    src: hostname.pppoe0
  notify: enable interfaces

- name: disable sndiod
  service:
    name: sndiod
    enabled: no
    state: stopped
